#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
STAMP="$(date -u +"%Y%m%d-%H%M%S")"
OUTPUT_ROOT="${OUTPUT_ROOT:-${ROOT_DIR}/tmp/dais-desk-visual-review-${STAMP}}"
SCREENSHOT_DIR="${OUTPUT_ROOT}/screenshots"
REPORT_FILE="${OUTPUT_ROOT}/DAIS_DESK_VISUAL_UX_REVIEW.md"
APPLESCRIPT="${ROOT_DIR}/apps/dais-desk/automation/DaisDesk.applescript"
LIVE_SCREENSHOT="${OUTPUT_ROOT}/active-window.png"
HEALTHCHECK_OUT="${OUTPUT_ROOT}/healthcheck.out"
HEALTHCHECK_ERR="${OUTPUT_ROOT}/healthcheck.err"
SCREENSHOT_OUT="${OUTPUT_ROOT}/active-window.out"
SCREENSHOT_ERR="${OUTPUT_ROOT}/active-window.err"

mkdir -p "${SCREENSHOT_DIR}"

shot_exists() {
  local name="$1"
  [[ -f "${SCREENSHOT_DIR}/${name}.png" ]]
}

shot_line() {
  local name="$1"
  local title="$2"
  if shot_exists "${name}"; then
    printf '| `%s` | %s | `screenshots/%s.png` |\n' "${name}" "${title}" "${name}"
  else
    printf '| `%s` | %s | missing |\n' "${name}" "${title}"
  fi
}

recommendation_line() {
  local scope="$1"
  local priority="$2"
  local recommendation="$3"
  local rationale="$4"
  printf '| %s | %s | %s | %s |\n' "${scope}" "${priority}" "${recommendation}" "${rationale}"
}

echo "Capturing modeled Dais Desk screens into ${SCREENSHOT_DIR}"
(
  cd "${ROOT_DIR}"
  DAIS_DESK_SCREENSHOT_DIR="${SCREENSHOT_DIR}" cargo test --manifest-path apps/dais-desk/Cargo.toml --test visual_smoke
)

LIVE_STATUS="not attempted"
if [[ "${CAPTURE_LIVE_WINDOW:-1}" == "1" && "$(uname -s)" == "Darwin" ]]; then
  if osascript "${APPLESCRIPT}" healthcheck >"${HEALTHCHECK_OUT}" 2>"${HEALTHCHECK_ERR}"; then
    if osascript "${APPLESCRIPT}" screenshotActiveScreen "${LIVE_SCREENSHOT}" >"${SCREENSHOT_OUT}" 2>"${SCREENSHOT_ERR}"; then
      LIVE_STATUS="captured active visible window: active-window.png"
    else
      LIVE_STATUS="visible app found, but active-window screenshot failed: $(tr '\n' ' ' <"${SCREENSHOT_ERR}")"
    fi
  else
    LIVE_STATUS="skipped live active-window screenshot: $(tr '\n' ' ' <"${HEALTHCHECK_ERR}")"
  fi
fi

{
  echo "# Dais Desk Visual UX Review"
  echo
  echo "**Generated:** $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
  echo
  echo "This report is generated by \`scripts/review-dais-desk-visual-ux.sh\`. It uses the Slint visual smoke workflow to capture every modeled Dais Desk screen, then applies a macOS-oriented review checklist to the screenshots. If a visible Dais Desk app is already running, the script also captures the active native window through AppleScript."
  echo
  echo "## Capture Status"
  echo
  echo "- Modeled screen screenshots: \`${SCREENSHOT_DIR}\`"
  echo "- Live active-window screenshot: ${LIVE_STATUS}"
  echo
  echo "## Screen Inventory"
  echo
  echo "| Screen | Area | Screenshot |"
  echo "| --- | --- | --- |"
  shot_line "home" "Home shell"
  shot_line "home-today" "Home / Today"
  shot_line "home-reading" "Home / Reading"
  shot_line "home-inbox-notifications" "Home / Inbox"
  shot_line "home-compose-media" "Home / Compose with media"
  shot_line "workflow-save-post" "Workflow / Save post"
  shot_line "workflow-reply-compose" "Workflow / Reply compose"
  shot_line "people-find-search" "People / Find"
  shot_line "people-relationship" "People / Relationship"
  shot_line "people-friends" "People / Friends"
  shot_line "people-followers" "People / Followers"
  shot_line "people-following" "People / Following"
  shot_line "people-watches-sources" "People / Watches and sources"
  shot_line "people-audience-groups" "People / Audience groups"
  shot_line "workflow-audience-compose" "Workflow / Audience to compose"
  shot_line "workflow-follower-approve" "Workflow / Follower approval"
  shot_line "people-blocks" "People / Blocks"
  shot_line "server-health" "Server / Health"
  shot_line "server-deliveries" "Server / Deliveries"
  shot_line "server-stats" "Server / Stats"
  shot_line "server-identity" "Server / Identity"
  shot_line "server-moderation" "Server / Moderation"
  shot_line "server-security" "Server / Security"
  shot_line "server-settings" "Server / Settings"
  shot_line "server-accounts" "Server / Accounts"
  echo
  echo "## Recommendations"
  echo
  echo "| Scope | Priority | Recommendation | Rationale |"
  echo "| --- | --- | --- | --- |"
  recommendation_line "Global shell" "High" "Move from text-heavy buttons to icon-plus-tooltip toolbar controls for repeated commands such as refresh, search, compose, account, and navigation." "This better matches macOS toolbar conventions and reduces horizontal pressure in the top bar."
  recommendation_line "Global shell" "High" "Add stable keyboard shortcuts for core navigation and command actions, then expose them in menus/tooltips rather than visible instructional text." "macOS users expect command-key workflows for frequent actions; this also improves automation coverage."
  recommendation_line "Global shell" "Medium" "Separate the active account switcher from search with a compact account menu using the account avatar/initial and instance label." "The current selector is useful but visually competes with search and primary commands."
  recommendation_line "Home / Today" "High" "Reduce row text density by making visibility, route, and status structured chips instead of prose inside the row body." "The primary reading task should scan like Mail or Messages: sender, subject/action, status, then detail on selection."
  recommendation_line "Inspector" "High" "Make inspector sections collapsible with consistent header/action placement." "The right pane is valuable, but dense repeated cards make it hard to predict where the primary next action lives."
  recommendation_line "Compose" "High" "Turn audience and protocol choices into segmented controls with current state clearly selected." "macOS users expect mode selection to show state; plain buttons do not make the active audience or route obvious enough."
  recommendation_line "Compose" "Medium" "Give direct/encrypted compose states stronger visual hierarchy and put recipient validation next to the recipient field." "Private-by-default posting needs confidence before send; validation should be local to the risky field."
  recommendation_line "People" "Medium" "Use a contacts-style split view for People screens: list on the left, selected actor/group details on the right." "This matches macOS address-book patterns and makes relationship management more predictable."
  recommendation_line "Watches / Sources" "Medium" "Distinguish Follow, Watch, Source, and Bundle with icons and persistent type badges." "These are different privacy and notification concepts; text-only rows make them too similar."
  recommendation_line "Server" "Medium" "Promote failed delivery, private-mode gate, and security status to compact status tiles at the top of Server screens." "Operational screens should surface exception state first and push routine detail lower."
  recommendation_line "Accounts" "High" "Make account switching a first-class macOS account menu and keep token management inside the Accounts screen." "Switching is a frequent identity action; token editing is a dangerous configuration action."
  recommendation_line "All screens" "Medium" "Standardize row heights, card radii, and button alignment; avoid nested framed panels where a simple split view or table would scan better." "The app is an operational social client, so density should be calm and regular rather than card-heavy."
  recommendation_line "All screens" "Medium" "Run screenshots at 1180x760, narrow desktop, and large desktop sizes before release gates." "Several toolbar and sidebar labels are long; responsive layout risk is highest around account labels and inspector text."
  recommendation_line "macOS" "High" "Package a real app bundle for local GUI automation and release smoke instead of relying on a debug binary or temporary bundle." "System Events and screenshot automation are much more reliable when LaunchServices sees a normal app identity."
  echo
  echo "## Review Checklist"
  echo
  echo "- Every screenshot is nonblank and at least 900x600; this is enforced by the Slint visual smoke test."
  echo "- Navigation follows the current three-mode model: Home, People, Server."
  echo "- Privacy-sensitive states should be visible before action, not hidden in inspector-only detail."
  echo "- Primary actions should use macOS-like toolbar/menu/segmented-control patterns where possible."
  echo "- Repeated dense information should prefer tables, split views, or source lists over nested cards."
  echo
  echo "## Next Implementation Slices"
  echo
  echo "1. Package a stable macOS Dais Desk app bundle and use it in live AppleScript automation."
  echo "2. Convert compose audience/protocol buttons into selected segmented controls."
  echo "3. Refactor row metadata into compact chips for visibility, route, unread, and failure states."
  echo "4. Add a release-gate mode that runs this script and attaches the generated report path to the release issue."
} >"${REPORT_FILE}"

echo "Visual UX report: ${REPORT_FILE}"
